
import __ASTRO_IMAGE_IMPORT_7CN2K from "./index/compressed/Display_nav.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_btn_nav%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z48i7y from "./index/compressed/Display_click_to_detail_page.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_click_card_item_move_to_detail_page%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z22r7XM from "./index/compressed/Display_image_picasso.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_image_cache_and_lazy_load%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1wrF9F from "./index/compressed/Display_pull_to_refresh.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_pull_to_refresh%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z165cRK from "./index/compressed/Display_recyclerView_different_card_styles.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_recyclerview_different_cards%2Findex.md";
import __ASTRO_IMAGE_IMPORT_pERki from "./index/compressed/Display_load_more.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_recyclerview_load_more%2Findex.md";
import __ASTRO_IMAGE_IMPORT_jPqUV from "./index/compressed/Display_request_and_render.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_request_and_card_list_render%2Findex.md";
import __ASTRO_IMAGE_IMPORT_JJ8qR from "./index/compressed/Display_tabbed.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_swip_views_with_tabs%2Findex.md";
export default new Map([["./index/compressed/Display_nav.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_btn_nav%2Findex.md", __ASTRO_IMAGE_IMPORT_7CN2K], ["./index/compressed/Display_click_to_detail_page.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_click_card_item_move_to_detail_page%2Findex.md", __ASTRO_IMAGE_IMPORT_Z48i7y], ["./index/compressed/Display_image_picasso.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_image_cache_and_lazy_load%2Findex.md", __ASTRO_IMAGE_IMPORT_Z22r7XM], ["./index/compressed/Display_pull_to_refresh.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_pull_to_refresh%2Findex.md", __ASTRO_IMAGE_IMPORT_1wrF9F], ["./index/compressed/Display_recyclerView_different_card_styles.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_recyclerview_different_cards%2Findex.md", __ASTRO_IMAGE_IMPORT_Z165cRK], ["./index/compressed/Display_load_more.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_recyclerview_load_more%2Findex.md", __ASTRO_IMAGE_IMPORT_pERki], ["./index/compressed/Display_request_and_render.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_request_and_card_list_render%2Findex.md", __ASTRO_IMAGE_IMPORT_jPqUV], ["./index/compressed/Display_tabbed.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fandroid_java_swip_views_with_tabs%2Findex.md", __ASTRO_IMAGE_IMPORT_JJ8qR]]);
		